name: CI

on:
  push:
    branches: [main]

env:
  LOCK_FILE: package-lock.json

jobs:
  testing_pipeline:
    runs-on: ubuntu-latest
    env:
      TEST_MONGODB_URI: ${{ secrets.TEST_MONGODB_URI }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Restore cached dependencies
        id: cache-deps-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            backend/node_modules
            frontend/node_modules
          key: npm-dep-cache-${{ runner.os }}-${{ hashFiles(env.LOCK_PATH) }}
        env:
          LOCK_PATH: '**/${{ env.LOCK_FILE }}'

      - name: Install dependencies
        if: steps.cache-deps-restore.outputs.cache-hit != 'true'
        run: npm clean-install && cd ../frontend && npm clean-install
        working-directory: backend

      - name: Lint
        run: npm run lint
        working-directory: backend

      - name: Unit tests
        run: npm run unittest
        working-directory: backend

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: e2e tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: npm run prepare:e2e
          wait-on: http://localhost:${{ env.PORT }}
          working-directory: frontend
        env:
          PORT: 3001

      - name: Cache dependencies
        if: steps.cache-deps-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            backend/node_modules
            frontend/node_modules
            ~/.cache/Cypress
          key: ${{ steps.cache-deps-restore.outputs.cache-primary-key }}

  deployment_pipeline:
    needs: testing_pipeline
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: backend
      REPOSITORY_NAME: ${{ github.event.repository.name }}
      PORT: 3001
    steps:
      - name: Initialize SSH variables
        run: |
          PRIVATE_KEY=`mktemp`
          echo "PRIVATE_KEY=$PRIVATE_KEY" >> $GITHUB_ENV
          chmod u=rw,go= $PRIVATE_KEY
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $PRIVATE_KEY
          KNOWN_HOSTS=`mktemp`
          echo "KNOWN_HOSTS=$KNOWN_HOSTS" >> $GITHUB_ENV
          echo "${{ secrets.SSH_KNOWN_PUBLIC_KEYS }}" > $KNOWN_HOSTS
          LOGIN_INFO=${{ secrets.SSH_USER_NAME }}@${{ secrets.SSH_HOST }}
          echo "LOGIN_INFO=$LOGIN_INFO" >> $GITHUB_ENV

      - name: Deploy to EC2
        run: |
          ssh -o UserKnownHostsFile=$KNOWN_HOSTS -i $PRIVATE_KEY $LOGIN_INFO '
            DOTENV="${{ env.BUILD_DIR }}/.env" &&
            LOCK_FILE=${{ env.LOCK_FILE }} &&

            if [ -d ~/${{ env.REPOSITORY_NAME }}/.git ]
            then
              cd ~/${{ env.REPOSITORY_NAME }} &&
              git fetch --all &&
              git reset --hard origin/main
            else
              rm -rf ~/${{ env.REPOSITORY_NAME }} &&
              git clone git@github.com:${{ github.repository }}.git &&
              cd ~/${{ env.REPOSITORY_NAME }} &&
              echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $DOTENV &&
              echo "PORT=${{ env.PORT }}" >> $DOTENV
            fi &&

            cd backend &&
            if ! cmp -s $LOCK_FILE $LOCK_FILE.old; then npm ci; fi &&
            cp $LOCK_FILE $LOCK_FILE.old &&
            cd .. &&

            cd frontend &&
            if ! cmp -s $LOCK_FILE $LOCK_FILE.old; then npm ci; fi &&
            cp $LOCK_FILE $LOCK_FILE.old &&
            cd .. &&

            cd ${{ env.BUILD_DIR }} &&
            npm run build &&
            cd .. &&
            pm2 restart ecosystem.config.js
          '

      - name: Health check
        id: health-check
        run: |
          HEALTH_CHECK_PASSED=false
          for ((i=1; i <= 80; i += 1))
          do
            sleep 1
            echo "Try $i/80"
            TITLE_ELEM="<title>Effortless Blogging Platform</title>"
            if curl -s http://13.53.88.241 | grep -q "$TITLE_ELEM"
            then
              echo "CHECK PASSED"
              HEALTH_CHECK_PASSED=true
              break
            fi
          done

          if ! $HEALTH_CHECK_PASSED
          then
            echo "CHECK FAILED"
            false
          fi

      - name: Rollback
        if: always() && steps.health-check.outcome == 'failure'
        run: |
          ssh -o UserKnownHostsFile=$KNOWN_HOSTS -i $PRIVATE_KEY $LOGIN_INFO '
            cd ~/${{ env.REPOSITORY_NAME }} &&

            PATTERN="^[a-f0-9]{40} HEAD@{\d+}: " &&
            PATTERN+="reset: moving to (origin/main|[a-f0-9]{40})$" &&

            PREV_COMMIT=`git reflog --no-abbrev-commit \
                           | grep -m 2 -P "$PATTERN" \
                           | tail -n 1 | head -c 40` &&

            git reset --hard $PREV_COMMIT &&

            cd ~/${{ env.REPOSITORY_NAME }}/${{ env.BUILD_DIR }} &&
            npm run build &&

            cd .. &&
            pm2 restart ecosystem.config.js
          '
