services:
  test-database:
    image: postgres:17-alpine
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -d postgres
      start_period: 30s
      start_interval: 1s

  test-limiter-data-store:
    image: mongo:8
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping")'
      start_period: 30s
      start_interval: 1s

  test-backend:
    image: shopping-list-backend
    build:
      context: backend
      dockerfile: dev.Dockerfile
    command: /bin/sh -c 'npx prisma db push && npx node --watch src/index.ts'
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./backend:/app
      - node_modules_test_backend:/app/node_modules
      - test_prisma_generated:/app/generated
    environment:
      DATABASE_URL: postgres://postgres:postgres@test-database
      LIMITER_DB_URL: mongodb://test-limiter-data-store
      LIMITER_DB_NAME: test-limiter-db
      PORT: 3000
      HOST: 0.0.0.0
      PASSWORD_HASH: 2b84ed4184c0fd093b62ef952b4e9025:3481b4599bdf5135a574714bd09bcc11765d6b65896939159ca0e42e615cf8cb5c6cad7f40ed274fa6a6efa0bd8eb1aa404316e623808aebb0af17910b80414b
      SECRET: secret
      RATE_LIMITER: off
    pull_policy: never
    depends_on:
      test-database:
        condition: service_healthy
      test-limiter-data-store:
        condition: service_healthy

volumes:
  node_modules_test_backend:
  test_prisma_generated:
