services:
  database:
    image: postgres:17-alpine
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      start_period: 30s
      start_interval: 1s

  limiter-data-store:
    image: mongo:8
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand(\"ping\")'"]
      start_period: 30s
      start_interval: 1s

  backend:
    image: typic-lists-backend
    build:
      context: backend
      dockerfile: dev.Dockerfile
    command: /bin/sh -c 'npx prisma db push && npx node src/index.ts'
    volumes:
      - ./backend:/app
      - node_modules_backend:/app/node_modules
      - prisma_generated:/app/generated
    environment:
      DATABASE_URL: postgres://postgres:postgres@database
      LIMITER_DB_URL: mongodb://limiter-data-store
      LIMITER_DB_NAME: limiter-db
      PORT: 3000
      HOST: 0.0.0.0
      PASSWORD_HASH: 27d3964aeb1e2b6e741889d3aa67a47f:fb1cc049dfa97f080f7282ee125f08d00a3293c4e25d72e8504f73411469cde28b884e372dec728e6dc383393269b83e7071636af3bae4773f4872aba6dd5b0d
      SECRET: secret
    pull_policy: never
    depends_on:
      database:
        condition: service_healthy
      limiter-data-store:
        condition: service_healthy

  frontend:
    image: typic-lists-frontend
    build:
      context: frontend
      dockerfile: dev.Dockerfile
    command: npx vite --host 0.0.0.0
    ports:
      - 127.0.0.1:5173:5173
    volumes:
      - ./frontend:/app
      - node_modules_frontend:/app/node_modules
    pull_policy: never

volumes:
  node_modules_backend:
  prisma_generated:
  node_modules_frontend:
  database:
