services:
  test-database:
    image: postgres:17-alpine
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -d postgres
      start_period: 30s
      start_interval: 1s

  test-limiter-data-store:
    image: mongo:8
    healthcheck:
      test: mongosh --eval 'db.runCommand("ping")'
      start_period: 30s
      start_interval: 1s

  test-backend:
    image: typic-lists-backend
    build:
      context: backend
      dockerfile: dev.Dockerfile
    command: /bin/sh -c 'npx prisma db push && npx node --watch src/index.ts'
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - ./backend:/app
      - node_modules_test_backend:/app/node_modules
      - test_prisma_generated:/app/generated
    environment:
      DATABASE_URL: postgres://postgres:postgres@test-database
      LIMITER_DB_URL: mongodb://test-limiter-data-store
      LIMITER_DB_NAME: test-limiter-db
      PORT: 3000
      HOST: 0.0.0.0
      PASSWORD_HASH: 27d3964aeb1e2b6e741889d3aa67a47f:fb1cc049dfa97f080f7282ee125f08d00a3293c4e25d72e8504f73411469cde28b884e372dec728e6dc383393269b83e7071636af3bae4773f4872aba6dd5b0d
      SECRET: secret
    pull_policy: never
    depends_on:
      test-database:
        condition: service_healthy
      test-limiter-data-store:
        condition: service_healthy

volumes:
  node_modules_test_backend:
  test_prisma_generated:
