name: CI

on:
  push:
    branches: [main]
    paths: ['backend/**', '.github/workflows/**']

jobs:
  preparation_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v5
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./backend/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm clean-install
        working-directory: backend

      - name: Tsc
        run: npm run tsc
        working-directory: backend

      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  deployment_pipeline:
    needs: preparation_pipeline
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Authenticate to Google Cloud
        id: gcp-auth
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Authenticate to Docker
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.gcp-auth.outputs.access_token }}
          registry: ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build, tag and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: >
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/typic-lists-backend/typic-lists-backend:${{ github.sha }},
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/typic-lists-backend/typic-lists-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: typic-lists
          region: ${{ vars.GCP_REGION }}
          image: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/typic-lists-backend/typic-lists-backend:latest
