name: CI

on:
  push:
    branches: [main]
    paths: ['backend/**', '.github/workflows/**']

jobs:
  preparation_pipeline:
    runs-on: ubuntu-latest

    services:
      test-database:
        image: postgres:17-alpine
        env:
          PGUSER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 127.0.0.1:5432:5432
        options: >-
          --health-cmd "pg_isready -d postgres"
          --health-start-period 30s
          --health-start-interval 1s

      test-limiter-data-store:
        image: mongo:8
        ports:
          - 127.0.0.1:27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand(\"ping\")'"
          --health-start-period 30s
          --health-start-interval 1s

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v5
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./backend/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm clean-install
        working-directory: backend

      - name: Generate Prisma client
        run: npx prisma generate
        working-directory: backend

      - name: Tsc
        run: npm run tsc
        working-directory: backend

      - name: ESLint
        run: npm run lint
        working-directory: backend

      - name: Integration tests
        run: npx prisma db push && node src/index.ts & npm test
        working-directory: backend
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost
          LIMITER_DB_URL: mongodb://localhost
          LIMITER_DB_NAME: test-limiter-db
          PORT: 3000
          HOST: 127.0.0.1
          PASSWORD_HASH: 27d3964aeb1e2b6e741889d3aa67a47f:fb1cc049dfa97f080f7282ee125f08d00a3293c4e25d72e8504f73411469cde28b884e372dec728e6dc383393269b83e7071636af3bae4773f4872aba6dd5b0d
          SECRET: secret

      - name: Apply all pending migrations to the database
        run: npx prisma migrate deploy
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

  deployment_pipeline:
    needs: preparation_pipeline
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Authenticate to Google Cloud
        id: gcp-auth
        uses: google-github-actions/auth@v3
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_WIF_SERVICE_ACCOUNT }}

      - name: Authenticate to Docker
        uses: docker/login-action@v3
        with:
          username: oauth2accesstoken
          password: ${{ steps.gcp-auth.outputs.access_token }}
          registry: ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build, tag and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: >
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/typic-lists-backend/typic-lists-backend:${{ github.sha }},
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/typic-lists-backend/typic-lists-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Google Cloud Run
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: typic-lists
          region: ${{ vars.GCP_REGION }}
          image: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/typic-lists-backend/typic-lists-backend:latest
